spring:
  application:
    name: pre_project
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/pre_test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  sql:
    init:
      mode: always

alert:
  slack:
    url: https://hooks.slack.com/services/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

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger

logging.level:
  org.hibernate.SQL: debug
  org.springframework.cache: TRACE
  org.springframework.cache.interceptor.CacheInterceptor: TRACE
